name: test version deploy
on:
  push:
    branches: [test]

jobs:
  main_CD_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install packages
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        env:
          SKIP_PREFLIGHT_CHECK: ${{ secrets.REACT_APP_SKIP_PREFLIGHT_CHECK }}
          REACT_APP_MAPBOX_TOKEN: ${{secrets.REACT_APP_MAPBOX_TOKEN}}
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://top-test-branch # 자신의 레포지토리로 변경해주세요.
